import test from 'node:test';import assert from 'node:assert/strict';import{resolveMorphology,ASSET_ACCOUNTING}from'../docs/visual-review/stage-02-morphology-clothing-spike/prototype.js';
const VOCAB={frame:['narrow','balanced'],torsoLeg:['torso_leaning','balanced','leg_leaning'],armLength:['short','average','long'],internalArm:['upper_arm_dominant','balanced','forearm_dominant'],clavicle:['compact','proportional','extended'],pelvic:['narrow','proportional','broad'],pose:['neutral','guard','punch','walk'],clothing:['fitted','outer']};
function combinations(keys=Object.keys(VOCAB),index=0,state={}){if(index===keys.length)return[state];const key=keys[index];return VOCAB[key].flatMap(value=>combinations(keys,index+1,{...state,[key]:value}))}
function separation(a,b){return Math.abs(b.x-a.x)}
test('resolver is deterministic and validates its closed state vocabulary',()=>{const s={frame:'narrow',torsoLeg:'leg_leaning',armLength:'long',clavicle:'extended',pelvic:'broad',pose:'punch',clothing:'outer'};assert.deepEqual(resolveMorphology(s),resolveMorphology(s));for(const key of Object.keys(VOCAB))assert.throws(()=>resolveMorphology({...s,[key]:'unknown'}),new RegExp(`unknown ${key}`))});
test('all 3,888 legal states resolve finite integer geometry deterministically',()=>{const states=combinations();assert.equal(states.length,3888);for(const state of states){const model=resolveMorphology(state);assert.deepEqual(model,resolveMorphology(state));for(const anchor of Object.values(model.anchors)){assert.ok(Number.isFinite(anchor.x));assert.ok(Number.isFinite(anchor.y));assert.ok(Number.isInteger(anchor.x));assert.ok(Number.isInteger(anchor.y))}for(const value of Object.values(model.measurements))assert.ok(Number.isFinite(value));assert.ok(model.components.every(id=>typeof id==='string'&&id.length>0));assert.ok(Number.isFinite(model.attachment.point.x));assert.ok(Number.isFinite(model.attachment.point.y))}});
test('frame is distinct from semantic pose and preserves shared grammar',()=>{for(const f of['narrow','balanced']){const w=resolveMorphology({frame:f,pose:'walk'});assert.equal(w.semantic.leftLeg,'forward');assert.equal(w.semantic.rightLeg,'back')}assert.notDeepEqual(resolveMorphology({frame:'narrow'}).anchors.shoulder_left,resolveMorphology({frame:'balanced'}).anchors.shoulder_left)});
test('#5A fixes standing height while redistributing torso length and total leg length',()=>{const torso=resolveMorphology({torsoLeg:'torso_leaning'}),balanced=resolveMorphology({torsoLeg:'balanced'}),leg=resolveMorphology({torsoLeg:'leg_leaning'});for(const m of[torso,balanced,leg]){assert.equal(m.measurements.totalHeight,56);assert.equal(m.measurements.torsoLength,m.anchors.hip_left.y-m.anchors.shoulder_left.y);assert.equal(m.measurements.totalLegLength,m.anchors.foot_left.y-m.anchors.hip_left.y)}assert.ok(torso.measurements.torsoLength>balanced.measurements.torsoLength);assert.ok(torso.measurements.totalLegLength<balanced.measurements.totalLegLength);assert.ok(leg.measurements.torsoLength<balanced.measurements.torsoLength);assert.ok(leg.measurements.totalLegLength>balanced.measurements.totalLegLength)});
test('internal arm variation moves elbow while preserving shoulder-to-wrist length',()=>{const c={armLength:'long',pose:'neutral'},u=resolveMorphology({...c,internalArm:'upper_arm_dominant'}),f=resolveMorphology({...c,internalArm:'forearm_dominant'});assert.equal(u.measurements.shoulderToWrist,f.measurements.shoulderToWrist);assert.deepEqual(u.anchors.hand_right,f.anchors.hand_right);assert.notDeepEqual(u.anchors.elbow_right,f.anchors.elbow_right)});
test('clavicle and pelvic values order valid skeletal separations',()=>{const shoulder=key=>{const m=resolveMorphology({clavicle:key});return separation(m.anchors.shoulder_left,m.anchors.shoulder_right)},hip=key=>{const m=resolveMorphology({pelvic:key});return separation(m.anchors.hip_left,m.anchors.hip_right)};assert.ok(shoulder('compact')<shoulder('proportional'));assert.ok(shoulder('proportional')<shoulder('extended'));assert.ok(hip('narrow')<hip('proportional'));assert.ok(hip('proportional')<hip('broad'))});
test('fitted and outer clothing resolve deterministically across both frames',()=>{for(const f of['narrow','balanced']){assert.ok(resolveMorphology({frame:f,clothing:'fitted'}).components.includes(`fitted.${f}`));assert.ok(resolveMorphology({frame:f,clothing:'outer'}).components.includes('outer.shared'))}});
test('moving equipment follows long-arm punch hand and face remains head-owned',()=>{const n=resolveMorphology({armLength:'long',pose:'neutral'}),p=resolveMorphology({armLength:'long',pose:'punch'});assert.deepEqual(p.attachment.point,p.anchors.hand_right);assert.notDeepEqual(n.attachment.point,p.attachment.point);for(const s of[{frame:'narrow'},{torsoLeg:'leg_leaning'},{clavicle:'extended'},{armLength:'long'},{pose:'guard'}]){const m=resolveMorphology(s);assert.deepEqual({eye_left:m.anchors.eye_left,eye_right:m.anchors.eye_right,nose:m.anchors.nose,mouth:m.anchors.mouth},{eye_left:{x:29,y:13},eye_right:{x:35,y:13},nose:{x:32,y:16},mouth:{x:32,y:19}})}});
test('asset growth accounting is quantitative and reproducible',()=>{assert.equal(ASSET_ACCOUNTING.logicalPresentationRequirements,3888);assert.equal(ASSET_ACCOUNTING.uniqueRasterComponents,9);assert.equal(ASSET_ACCOUNTING.avoidedVariants,3879);assert.equal(ASSET_ACCOUNTING.classificationCounts.METADATA_ONLY,4)});
